apiVersion: celery.rrethy.io/v1alpha1
kind: ValidationRules
metadata:
  name: configmap-secret-policies
spec:
  rules:
    - name: configmap-size-limit
      expression: |
        !has(object.data) && !has(object.binaryData)
      message: "ConfigMap values should be checked for size limits (simplified check)"
      target:
        kind: ConfigMap
    
    - name: secret-type-required
      expression: |
        has(object.type) && object.type != ''
      message: "Secret must have a type specified"
      target:
        kind: Secret
    
    - name: no-plain-passwords
      expression: |
        !has(object.data)
      message: "Secrets should be validated for sensitive key names (simplified check)"
      target:
        kind: Secret
    
    - name: immutable-configs-prod
      expression: |
        object.metadata.labels.environment != 'production' ||
        (has(object.immutable) && object.immutable == true)
      message: "Production ConfigMaps should be immutable"
      target:
        kind: ConfigMap
        labelSelector: "environment=production"
