apiVersion: celery.rrethy.io/v1alpha1
kind: ValidationRules
metadata:
  name: configmap-secret-policies
spec:
  rules:
    - name: configmap-size-limit
      expression: |
        !has(object.data) && !has(object.binaryData) ||
        (
          (!has(object.data) || object.data.all(key, value, size(value) <= 1048576)) &&
          (!has(object.binaryData) || object.binaryData.all(key, value, size(value) <= 1048576))
        )
      message: "ConfigMap values should not exceed 1MB"
      target:
        kind: ConfigMap
    
    - name: secret-type-required
      expression: |
        has(object.type) && object.type != ''
      message: "Secret must have a type specified"
      target:
        kind: Secret
    
    - name: no-plain-passwords
      expression: |
        !has(object.data) ||
        !object.data.exists(key, _, 
          key.matches('(?i).*(password|passwd|pwd).*')
        )
      message: "Secrets should not have keys containing 'password' - use external secret management"
      target:
        kind: Secret
    
    - name: immutable-configs-prod
      expression: |
        object.metadata.labels.environment != 'production' ||
        (has(object.immutable) && object.immutable == true)
      message: "Production ConfigMaps should be immutable"
      target:
        kind: ConfigMap
        labelSelector: "environment=production"
