name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'go.work.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Sync workspace
      run: go work sync
    
    - name: Create bin directory
      run: mkdir -p bin
    
    - name: Run tests
      run: make test
    
    - name: Run linter
      run: make lint
    
    - name: Check formatting
      run: |
        make fmt
        if [ -n "$(git diff --name-only)" ]; then
          echo "Code is not formatted. Please run 'make fmt'"
          git diff
          exit 1
        fi
    
    - name: Run go vet
      run: make vet
    
    - name: Verify go mod tidy
      run: |
        make tidy
        if [ -n "$(git diff --name-only)" ]; then
          echo "go.mod or go.sum is not tidy. Please run 'make tidy'"
          git diff
          exit 1
        fi